version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.13.4

env:
  - SCALAJS_BUILD=     ADOPTOPENJDK=8
  - SCALAJS_BUILD=     ADOPTOPENJDK=11
  - SCALAJS_BUILD=     ADOPTOPENJDK=17
  - SCALAJS_BUILD=true ADOPTOPENJDK=8
  - SCALAJS_BUILD=true ADOPTOPENJDK=11
  - SCALAJS_BUILD=true ADOPTOPENJDK=17

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

notifications:
  email:
    - seth.tisue@lightbend.com
